### ISSUE TITLE
Document JSON output

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#10]
See : http://www.chronoengine.com/forums/viewtopic.php?f=12&t=86233#p305836

I have a CC connection with one table and two existing one-to-one relations. This is working perfectly. I want to display in the connection list the number of times each user has logged in (using Joomlatools Logman extension and DB table). I have it working now by including the following in the custom list:

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/57
