### ISSUE TITLE
Document how to remove a field

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#15]
Add https://docs.google.com/document/d/13XUYFIkWTVcLyPkFKrAQtDu_0sOd78OHRH_1Ld6XFYQ/edit to http://developer.joomlatools.com/extensions/docman/templates/overrides.html#how-to-change-the-frontend-document-form

Complete overview in the associated development ticket: https://timble.assembla.com/spaces/joomlatools-docman/tickets/535-add-access-level-to-frontend-form/details#

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/56
