### ISSUE TITLE
How to boot the framework from the command line

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#17]
See : http://www.joomlatools.com/membercenter/forums/topic/3112

```
// This is useful in CLI mode
if (!class_exists('Koowa'))
{
    if (!defined('JDEBUG')) {
        define('JDEBUG', 0);
    }

    JPluginHelper::importPlugin('system');
    JDispatcher::getInstance()->trigger('onAfterInitialiase');
}

return class_exists('Koowa');
```

**Comment by johanjanssens** [comment]
@ercanozkaya Does http://developer.joomlatools.com/extensions/docman/php-api.html#a-complete-script this cover how to boot from the command line ?

**Comment by ercanozkaya** [comment]
@johanjanssens Yes but in a different way. The one in the link only imports the Koowa plugin as opposed to all system plugins.

**Comment by johanjanssens** [comment]
@ercanozkaya So which one should we use or document ? Or should we do both and explain the difference ? Are they for different use cases ?

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/55
