### ISSUE TITLE
How to play video using JWPlayer

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#18]
- http://www.joomlatools.com/support/forums/topic/3295
- http://www.joomlatools.com/support/forums/topic/3309-simple-instructions-on-using-external-video-player

**Comment by stevenrombauts** [comment]
Bad commit references above ... I've deleted them ... sorry.

**Comment by tomjanssens** [comment]
Documentation has been added at http://www.joomlatools.com/extensions/docman/documentation/tutorials/play-and-stream-video-files.html#using-jwplayer

Closing this issue.
