### ISSUE TITLE
Extending modules

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#23]
See:
- http://www.joomlatools.com/support/forums/topic/3262
- https://timble.assembla.com/spaces/joomlatools-docman/tickets/694?comment=602279623#comment:602279623
- http://docs.joomla.org/Adding_custom_fields_to_the_article_component

DOCman now sets module parameters as model states which lets you extend modules easily by just adding a form parameter like:

    <field name="created_by" default="62" type="hidden" />

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/54
