### ISSUE TITLE
Rewrite Introduction 

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#27]
"developer zone is more then just the tools we have"

http://developer.joomlatools.com/index.html#introduction

<pre><code>
If you are a web developer and you create custom Joomla websites or components, you require tools that allow you to focus on what matters most: solving your client's problems.

On our Joomlatools developer portal you will find developer tools, tutorials, code snippets and examples we use ourselves to speed up, improve and simplify all our Joomla related development work.

In the months to come we will be adding more goodies. Check back often and happy coding!
</code></pre>

**Comment by tomjanssens** [comment]
What's the idea of the ticket? This is the text I removed when changing the homepage.

I don't think we need such introduction, at least not this much of text, examples:

* https://developer.zendesk.com/
* https://developers.google.com/
* https://developers.facebook.com/

**Comment by stevenrombauts** [comment]
@tomjanssens  I think we missed this one after migrating it, it's already closed on [Assembla](https://timble.assembla.com/spaces/joomlatools-documentation/tickets/27#/activity/ticket:)  and precedes your recent changes.
