### ISSUE TITLE
Create Gitbook Apiary Plugin and Update Style

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#29]
Work has already progressed. This plugin pre-renders api docs and pushes the content to the page.content property in Gitbook. 
 
Done:
* add a config variable that lets you list the docs you want to convert 
* fix the styling for the rendered pages. combination jquery plugin/css.

Todo:
* add template path to config variable and pass that to the parser 
* add package dependancies
* clean up the styling even more. 
* we may want to consider forking the bootstrap-mixin and make some changes to suit our needs.

**Comment by stevenrombauts** [comment]
re#29 committing the build separately

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/105b516eb940e2a894c5297029d09d7204551654|joomlatools-documentation:105b516eb9]]

**Comment by stevenrombauts** [comment]
re#29 loading files via config var in book.json, styling apiary output, adding php examples to each request

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/e6b6dd176346b9380428daa166af1708aad46bdf|joomlatools-documentation:e6b6dd1763]]

**Comment by stevenrombauts** [comment]
@johanjanssens If you want to see how this is looking right now you can just pull down this branch and look at the build/extensions/api.html file in the browser.

**Comment by stevenrombauts** [comment]
re#29 - remove the need to symlink to bare.jade template. ported mixins so we can customize. fixed style rules for collapseables .

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/4f89deea19594e0fb1a93664a78b34d23da9923d|joomlatools-documentation:4f89deea19]]

**Comment by stevenrombauts** [comment]
re#29 adding plugin events to the document

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/0e4d0e5e247da029fb98dcee5e92e03179cb2a44|joomlatools-documentation:0e4d0e5e24]]

**Comment by stevenrombauts** [comment]
re#29 - remove the need to symlink to bare.jade template. ported mixins so we can customize. fixed style rules for collapseables .

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/0ccb6986910eefd4a36a8ce8869caf2391d7e0b0|joomlatools-documentation:0ccb698691]]

**Comment by stevenrombauts** [comment]
@johanjanssens

I have fixed all the major visual issues with this. 
Also, I've moved the relevant jade mixin methods to our plugin which eliminates the need to symlink the template. 

This is ready for feedback. Specifically I am looking for suggestions about the placement of the PHP code. Right now its in the description part of the request types. Its possible that we may put this in its own 'collapsable' along with Request and Response.
(https://github.com/joomlatools/developer.joomlatools.com/blob/feature/29-aglio-plugin-and-styling/build/extensions/docman/api.html)

Once we finalize that, this is ready, and then we can make some adjustments for Nooku and other docs.

**Comment by stevenrombauts** [comment]
@cameronbarr Is there a wiki somewhere that outlines the steps to make this work locally so I can test ?

**Comment by stevenrombauts** [comment]
This is looking good. I would make a clear distinction between  the following API's. 

- PHP API
- Web API
- Event API (Would not name this Relevant Plugin Events as the events are useful everywhere, not only in plugins).

Your start description would then be something like :

The DOCman Web API is a Restful JSON API. The default JSON response documents are inspired by the JSON API specification. For a deeper look at how the core JSON format actually gets built have a look our write up about JSON at http://guides.nooku.org/JSON.html .

Note : the whole fact that our Joomlatools extensions are build on Nooku is not somethign we need to repeat everywhere. This is something for the framework docs. 

Also here we would have a parent framework/api page that contains the generic information about the API itself with the relevant links to Nooku.

**Comment by stevenrombauts** [comment]
re#29 - style rule fix for collapseable items

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/64e27f0ff938123d2da40cc56fd997a2e459b1fa|joomlatools-documentation:64e27f0ff9]]

**Comment by stevenrombauts** [comment]
re#29 - PHP and Event API, description and collection move

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/15ff568ab3d819c231b9b1aa147f1b9efc2500a8|joomlatools-documentation:15ff568ab3]]

**Comment by stevenrombauts** [comment]
re#29 - aligning "See" section method format

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/56ae19ed615616ac13fc2be559c3437953dea5ff|joomlatools-documentation:56ae19ed61]]

**Comment by stevenrombauts** [comment]
Ok @johanjanssens, have a look at that and let me know what you think.

**Comment by stevenrombauts** [comment]
Looking good. In relation with naming used. I would consider to change 'document' to Individual Document

So you have 

- Document Collection
- Individual Document

I would also change the heading to Document instead of Documents, the resource type is document, not documents. 

Does that make sense ?

**Comment by stevenrombauts** [comment]
The parameters are not correct :

1. Document Collection

- view and layout dont' make sense in a 'browse' scenario, view and layout only make sense when you do render and render to a string.
- slug desscription is wrong.

There are additional model states see : ComDocmanModelDocuments not all of those are public, some are internal see. Ask Ercan for feedback on the states we want to mention here.

2. Additionally, in NF it's possible to get a individual entity using any of the unique columns in the database for a document this is 

- 'id'
- 'uuid'
- 'slug' (slug for documents are also unique)

**Comment by stevenrombauts** [comment]
re#29 - Adding to the parameters section of the markdown. Renaming document model

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/05fcbd3fab027e66d79848de2f50402114014701|joomlatools-documentation:05fcbd3fab]]

**Comment by stevenrombauts** [comment]
@ercanozkaya

Could you have a look at the following (docman) view=documents parameter list in API Blueprint format and tell me if I am missing anything. I'd also like to make sure I am not including anything that's not accessible through the Web API, i.e. should I include storage_path, image, etc?:

+ Parameters
    + category (optional, int, `24`) ... Is used to specify the category that the list of documents should belong to.
    + category_children (optional, bool, 1) ... If `category` is set, this setting will toggle the inclusion of documents of child categories is the result.
    + sort (optional, string, `title`) ... Column used to sort the results in the response.
    + direction (optional, string, `asc`) ... The direction of the resulting sort. The default is 'asc'.
    + offset (optional, int, `6`) ... Defines the beginning of the subset of entities.
    + limit (optional, int, `2`) ... Defines the number entities that should be returned in the response.
    + created_by (optional, int, `690`) ... Joomla userid of the document creator.
    + search_date (optional, date, `2013-09-27`) ... Date that the document was created on.
    + day_range (optional, int, `30`) ... The number of days before or after the `search_date` . Note: `search_date` defaults to the current time if not set.
    + status (optional, string, `published`) ... Status of the document
    + search (optional, string, `cake`) ... A keyword to search for the documents for. Used in combination with `search_by`
    + search_by = `exact` (optional, string, `exact`) ... Used to define the type of `search` strategy used.
       

@johanjanssens, have removed the 'view' from the Parameters section of the Documents collection and made it part of the permanent URL template.

**Comment by stevenrombauts** [comment]
I wouldn't document storage_path, image etc as they are used internally only. 

From the above list: 
status is only applicable to either backend or to super users. Otherwise it's forced to published. So I'd remove that.
search_by: might include accepted values here they are "exact", "any", and "all".

The rest looks good.

**Comment by stevenrombauts** [comment]
re#29 - committing build and minor change

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/042d05d6b024bbd148e5bd57e4747c3bd157c832|joomlatools-documentation:042d05d6b0]]

**Comment by stevenrombauts** [comment]
re#29 - committing build

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/8ebbbbbb0244b44347ec00d862a4207087f23607|joomlatools-documentation:8ebbbbbb02]]

**Comment by stevenrombauts** [comment]
re#29 - fixing display for api sections

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/cdbaa264bb0a251a6487e08bd8c666d718382e1b|joomlatools-documentation:cdbaa264bb]]

**Comment by stevenrombauts** [comment]
re#29 - adding apiary node_module

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/4932662c36c0fe1eac2e69bd6480e1e00ad3c563|joomlatools-documentation:4932662c36]]

**Comment by stevenrombauts** [comment]
re #29 - updating package to include aglio

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/30ed0b43006ba1019882eaab6b0b5bb41c412a37|joomlatools-documentation:30ed0b4300]]

**Comment by stevenrombauts** [comment]
re#29 - remove +Nav call from the jade template

Branch: feature/29-aglio-plugin-and-styling
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/c76aeb97ebc29f7eb3f0d7a8e8ed7a57c25f6098|joomlatools-documentation:c76aeb97eb]]

**Comment by stevenrombauts** [comment]
@cameronbarr Since we decided to move to Jekyll, can this be marked invalid, or can part of the work here be re-used ?

**Comment by stevenrombauts** [comment]
@johanjanssens. I would keep this one around a little while longer, until after Tom is done with the Jekyll business and then we can re-assess. The markup is good, and there may be something we can still do with it. Apiary has a Ruby gem that produces some markup that we may be able to use to render the html. I'll review that some more and then comment here.

**Comment by stevenrombauts** [comment]
@cameronbarr Sounds like a plan.

**Comment by stevenrombauts** [comment]
Update: this branch has been updated with master.

**Comment by tomjanssens** [comment]
Discontinuing this issue, closing and marked as Invalid.

The work is nothing more than a [API Blueprint Markdown file](https://github.com/joomlatools/developer.joomlatools.com/blob/fe01a77490deab7363ed037db038b0d2b21f4956/extensions/docman/api.md) that is parsed to HTML using a custom developed [Aglio plugin](https://github.com/joomlatools/developer.joomlatools.com/blob/70400dd9eaad1aac3d6c5d6026e8f2f018fd10a7/node_modules/gitbook-plugin-apiary/index.js)

We have the same API Blueprint Markdown on Apairy.io: http://docs.joomlatoolsdocman.apiary.io/. Cool thing of Apiary.io is that is has a [Console](https://docs.apiary.io/tools/interactive-documentation/#console) that can get data from our demo server to test API calls.

We will focus solely on our Apiary.io documentation.

**Comment by tomjanssens** [comment]
Apiary documention work continues in #82.
