### ISSUE TITLE
Add entities list to plugins documentation 

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#31]
Per request by a user for a list of events, it has been reasoned that a list of entities in combination with the explanation from the new framework plugin piece will be good. If you know the entities and how the plugin system works, you know all the events.

**Comment by stevenrombauts** [comment]
@cameronbarr I noticed you logged 0.5 hours for this but no commits related to the ticket ? Did you do any work here ?

**Comment by stevenrombauts** [comment]
Yes, but ended up recording all work and time under the related ticket #29 I believe.

**Comment by stevenrombauts** [comment]
@cameronbarr No problem in future let’s try to keep timelogs focussed per ticket.

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/53
