### ISSUE TITLE
Generic Plugin Events

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#35]
For the generic plugin events, i.e. on, some background in relation to plugins and then a specific usage example would be good. When, and Why

The framework does fire two events. One event that includes the components and entity name and one generic event. See https://github.com/nooku/nooku-framework/blob/master/code/libraries/koowa/libraries/command/handler/event.php#L144

The generic events to intercept actions application wide. They are very powerful and are best used in combination with the Koowa plugin group.

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/52
