### ISSUE TITLE
DOCman template documentation

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#37]
Move to http://developer.joomlatools.com/extensions/docman/templates.html:

- [x] http://www.joomlatools.com/support/forums/topic/1138-20-getting-started-with-template-overrides

Will not fix:
- http://www.joomlatools.com/support/forums/topic/4282-how-to-change-the-h1-header-font-size#comment-21416: DOCman relies on the Joomla template for heading styles, these are very specific issues. We already have information how to add custom CSS.
- http://www.joomlatools.com/support/forums/topic/4270, the person found how to handle custom CSS only his CSS was wrong, not gonna move it to documentation since it is very specific.

**Comment by stevenrombauts** [comment]
Additonal notes : 

- The goal is to create specific DOCman template documentation information, including

-- An overview of the view and template structure
-- An overview of docman specific tags, filters and helper

- Additionally we also want to move some of the common template specific FAQ from the tuorials : http://www.joomlatools.com/support/forums/topic/1138-20-getting-started-with-template-overrides

**Comment by tomjanssens** [comment]
http://www.joomlatools.com/support/forums/topic/1138-20-getting-started-with-template-overrides has been added.

Need to look into the other references so can get released.

**Comment by tomjanssens** [comment]
Updated the description to reflect that the remaining content doesn't have much added value by moving it to the developer documentation.
