### ISSUE TITLE
[framework] Add Behavior Sections from Guides

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#38]
I've written serviceable intros/summaries for each of the MVC and Database parts in the guides. and will bring them to the framework portion of the developer docs. This is for completeness and to support #14 and other behavior explanations in general

**Comment by stevenrombauts** [comment]
re #38 - adding behavior set from new guides

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/71e454628633b848cd3fbf1baff1f840b31fbab7|joomlatools-documentation:71e4546286]]

**Comment by stevenrombauts** [comment]
re #38 - adding behavior set from new guides

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/60fc83a1db62ad2c2d4531633c85b30912ee43e1|joomlatools-documentation:60fc83a1db]]

**Comment by stevenrombauts** [comment]
re #38 - adding more to the behavior intro

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/602d3e27b5132e997e4b4674945f9613fdf8baf0|joomlatools-documentation:602d3e27b5]]

**Comment by stevenrombauts** [comment]
re #38 - adding behavior set from new guides

Branch: staging
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/71e454628633b848cd3fbf1baff1f840b31fbab7|joomlatools-documentation:71e4546286]]

**Comment by stevenrombauts** [comment]
re #38 - adding more to the behavior intro

Branch: staging
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/602d3e27b5132e997e4b4674945f9613fdf8baf0|joomlatools-documentation:602d3e27b5]]

**Comment by stevenrombauts** [comment]
re #38 - adding behavior set from new guides

Branch: staging
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/60fc83a1db62ad2c2d4531633c85b30912ee43e1|joomlatools-documentation:60fc83a1db]]

**Comment by stevenrombauts** [comment]
re #38 - Removed Gitbook file

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/daa52c968e5b6e17e8c7058ea5a34ad4874961f5|joomlatools-documentation:daa52c968e]]

**Comment by stevenrombauts** [comment]
re #38 - Added Behaviors

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/a30fa68ed1a27b811b2b7a9f64efcf498757f01a|joomlatools-documentation:a30fa68ed1]]

**Comment by stevenrombauts** [comment]
This branch has been uppdated with master.

**Comment by stevenrombauts** [comment]
re #38 - Removed unused directory

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/0a2615bc18994b5ee961e79c5be4b0f86e49e9fa|joomlatools-documentation:0a2615bc18]]

**Comment by stevenrombauts** [comment]
re #38 - Moved articles to correct structure and did some minor content improvements

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/2fe998a0acb1ca3b9fb1d20b2ba4aa08af949992|joomlatools-documentation:2fe998a0ac]]

**Comment by stevenrombauts** [comment]
re #38 - Parameterizable behavior has been moved and finished in #52

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/5ea60a9a3c88104759b3bfdf01822401a3535720|joomlatools-documentation:5ea60a9a3c]]

**Comment by stevenrombauts** [comment]
re #38 - Moved articles to correct structure

Branch: feature/38-adding-behaviors
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/0183b892d1785618d2550528466531e60960cb46|joomlatools-documentation:0183b892d1]]

**Comment by tomjanssens** [comment]
Merged branch to production and deployed.
