### ISSUE TITLE
Document how to change thumbnails sizes

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#41]
Write a small tutorial based on the answer given here:

http://support.joomlatools.com/forums/topic/4859-thumbnail-size-for-docman-211

**Comment by stevenrombauts** [comment]
@cameronbarr I noticed you logged 0.5h here but no commits to the ticket ? Did you already work on this one ?

**Comment by stevenrombauts** [comment]
No written work. Time taken discussing the issue with Arunas back in May and reviewing the forum post, etc. Took about a half hour

**Comment by tomjanssens** [comment]
@robinpoort can you check if the CSS is correct? I changed it a little from the initial answer of Arunas on the support.

**Comment by robinpoort** [comment]
@tomjanssens Is this still valid? Can't find the info on the staging site anymore.

**Comment by tomjanssens** [comment]
Strange, can't get it deployed on staging either.

Deployed to production: http://developer.joomlatools.com/extensions/docman/templates/overrides.html#how-to-change-the-thumbnail-size can you check?

**Comment by robinpoort** [comment]
@tomjanssens Fixed two typos and pushed to master.

The only thing you changed is making the override the same as for the icons right? That has been tested thoroughly so this will work as well.

This change also makes sure the change is also applied to DOCman and not for FILEman if that is also active on your site, which is a good thing!

**Comment by tomjanssens** [comment]
Thanks, closing the issue.
