### ISSUE TITLE
Rework and Add Introductory Vagrant Article

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#44]
Take Sitepoint Vagrant article and rework for our usage. Leading into Joomla development instead. 

See: http://www.sitepoint.com/re-introducing-vagrant-right-way-start-php/

Can maybe pull in elements from our 2 other articles.

**Comment by stevenrombauts** [comment]
@cameronbarr I noticed you logged 0.5h for this ticket, was any work already done on this one ?

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/50
