### ISSUE TITLE
Document $document entity object api

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#46]
Write a basic topical guide to illustrate some useful methods that DOCman developers may use to interact with the $document, and $documents entity objects in templates (and elsewhere). 

* There can be some some light reference to behaviors/mixin to the interface without getting to technical (just highlight the fact that methods are added to the interface, i.e. `ComDocmanDatabaseBehaviorPermissible::getGroups()`). 
* Special mention of Parameterizable and getParams
* Possibly list each method in the interface and highlight its return

See: 
http://support.joomlatools.com/forums/topic/5028

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/49
