### ISSUE TITLE
[docman] How to setup an individual user documents area

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#47]
See : http://support.joomlatools.com/forums/topic/3327-how-to-setup-an-individual-user-documents-area

In response to a question:

"Hi I want to know if Docman can be used to upload pdf files and that only one user can see it. Every user in the site will see only their pdf files. Can this be done? Because all users has the range: registered.”

Todo :

- Review existing tutorial (http://support.joomlatools.com/forums/topic/3327-how-to-setup-an-individual-user-documents-area)
- Add additional gif video’s
- Make blog post

**Comment by tomjanssens** [comment]
Already handled: http://www.joomlatools.com/extensions/docman/documentation/tutorials/setup-an-individual-user-documents-area.html
