### ISSUE TITLE
[fileman] Simple file management with FILEman

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#48]
See : http://www.joomlatools.com/membercenter/forums/topic/987-20-group-and-permission-management-how-to#comment-3942

Turn the above post on the forums into a tutorial with screenshots. Use a simpiler scenario like three groups, teacher, Class A and Class B. Post on blog, demo site and in tutorials section on member center. (to be created).

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/31
