### ISSUE TITLE
[docman] Hidden document download links

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#49]
See : http://www.joomlatools.com/membercenter/forums/topic/1003

A common scenario people want to create, is the ability to have public 'hidden' document download links they can distribute through email or other means. My above comment describes two techniques to do this to do this in a manageble way. This makes for a very useful tutorial with screenshots and extra information to demonstrate the power of DOCman 2.

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/30
