### ISSUE TITLE
Platform documentation

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#55]
Start the documentation about Joomla Platform.

See:

* https://roots.io/bedrock/
* https://roots.io/bedrock/docs/
* https://roots.io/twelve-factor-01-codebase/
* http://www.sitepoint.com/12-factor-apps-methodology-implement-apps-appfog
* http://www.clearlytech.com/2014/01/04/12-factor-apps-plain-english/

**Comment by stevenrombauts** [comment]
re #55 - Added to navigation

Branch: feature/55-platform
Commit: [[url:https://github.com/joomlatools/developer.joomlatools.com/commit/f1bdfa879c6c27e53e866058936593c237e8fc5d|joomlatools-documentation:f1bdfa879c]]

**Comment by stevenrombauts** [comment]
@johanjanssens I've drafted some documentation for the platform for you to review at http://developer.joomlatools.xxx/tools/platform.html : 

* Summarised the 12 factor app methodology, made it a little easier to read, tried to add examples relating to platform where possible. Above all, tried to keep it short.
* Copied the README features into the introduction page, don't think we need much more.
* Getting started page is the basic installation instructions
* The other pages are based on Bedrock docs: Folder structure, Config files, Env vars, Deployment, Composer. I am guessing you'll want to add stuff to these :)

Let me know your thoughts!

**Comment by johanjanssens** [comment]
@stevenrombauts  Excellent work my friend. As far as I'm concerned this one is ready to roll. Go go!

**Comment by stevenrombauts** [comment]
Great. This one's out in the wild: http://developer.joomlatools.com/tools/platform.html

**Comment by johanjanssens** [comment]
@stevenrombauts Still need to update frontpage too : http://developer.joomlatools.com/

**Comment by tomjanssens** [comment]
Would it make sense if we put the menu item on the same level as 'Framework'?

**Comment by johanjanssens** [comment]
@tomjanssens We could, or we could put it into the 'tools' section. It's one of our major developer products, to make it more visible we could have it separate ?

**Comment by tomjanssens** [comment]
@stevenrombauts Made all the remaining changes, including the move of the Platform link to a top level link.

Testable: http://developer.joomlatools.xxx/platform/

Can you remove the server redirect from http://developer.joomlatools.xxx/platform/ to http://developer.joomlatools.xxx/tools/platform.html? Afterwards you can deploy.

**Comment by johanjanssens** [comment]
Go go :)

**Comment by stevenrombauts** [comment]
Redeployed, platform has been moved to same level as Extensions and Framework: http://developer.joomlatools.com/platform/

Thanks @tomjanssens  :)
