### ISSUE TITLE
Update docs for console 1.4

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#59]
Update the docs to add the new commands in joomla-console 1.4 and joomla-vagrant 1.3.1

**Comment by stevenrombauts** [comment]
@tomjanssens I've created a Commands page that is a 100% complete listing of the joomla-console commands and their arguments and options. 

Example on staging: http://developer.joomlatools.xxx/tools/console/commands.html

Been playing with automatically generating it from the console itself, and this works great: the console can give us a JSON file containing all commands, and Jekyll now parses that file. We'll never need to write separate documentation for this again (just fetch the json file and commit). 

The commands that do require a bit more explanation are also covered. Adding the text to the joomla-console itself improves it command-line usage (using `joomla help <command>`) and improves the online documentation in go. See this [example](https://github.com/joomlatools/joomla-console/blob/e78f095e1e466c80b45a1c9da04cc24069eb646c/src/Joomlatools/Console/Command/Site/Create.php#L41-L53). 

We might want to present some things in a different way so I'm assigning to you to take a look and hear your thoughts on the matter?

**Comment by johanjanssens** [comment]
@stevenrombauts  Good work. I like it.

**Comment by stevenrombauts** [comment]
Danke sehr @tomjanssens  :)

**Comment by tomjanssens** [comment]
Deployed: http://developer.joomlatools.com/tools/console/commands.html
