### ISSUE TITLE
Setup blog

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/developer.joomlatools.com#63]
Setup blog and migrate Nooku & Joomlatools blog posts.

## From http://www.joomlatools.com/blog

* http://www.joomlatools.com/blog/2013/11/composer-for-joomla-an-extension-installer-for-developers.html
* http://www.joomlatools.com/blog/2013/08/joomla-in-a-box.html
* http://www.joomlatools.com/blog/2015/06/new-joomla-vagrant-box-released.html
* http://www.joomlatools.com/blog/2015/05/extend-joomla-console-with-plugins.html
* http://www.joomlatools.com/blog/2014/11/logman-2-api-documentation-available.html
* http://www.joomlatools.com/blog/2014/03/with-a-little-help-from-your-friends.html
* http://www.joomlatools.com/blog/2014/03/joomla-console.html

## From http://www.nooku.org/blog

* http://www.nooku.org/blog/2015/06/backbone-joomla-and-nooku-an-instant-friendship/
* http://www.nooku.org/blog/2015/01/getting-started-with-nooku-and-our-tutorial-component/
* http://www.nooku.org/blog/2015/05/nooku-framework-21-released/
* http://www.nooku.org/blog/2015/02/custom-joomla-extensions-with-nooku/
* http://www.nooku.org/blog/2015/01/a-happy-nooku-year-to-all-of-you/
* http://www.nooku.org/blog/2014/12/special-delivery-from-the-composer-express/
* http://www.nooku.org/blog/2012/01/getting-started-with-foreign-keys/
* http://www.nooku.org/blog/2011/02/nginx-for-the-world-and-joomla/

## Backlog

* http://www.nooku.org/blog/2011/11/the-magic-of-primary-and-unique-keys/
* http://www.nooku.org/blog/2011/11/form-validation-with-nooku-framework/
* http://www.nooku.org/blog/2011/10/the-magic-of-file-uploads-with-com_files/
* http://www.nooku.org/blog/2011/08/say-hello-to-the-dynamic-module-injector/
* http://www.nooku.org/blog/2010/12/split-views-using-nooku-framework/

**Comment by johanjanssens** [comment]
@tom here is the list of links you asked about. 

1. From http://www.joomlaools.com/blog

- http://www.joomlatools.com/blog/2013/11/composer-for-joomla-an-extension-installer-for-developers.html
- http://www.joomlatools.com/blog/2013/08/joomla-in-a-box.html
- http://www.joomlatools.com/blog/2015/06/new-joomla-vagrant-box-released.html
- http://www.joomlatools.com/blog/2015/05/extend-joomla-console-with-plugins.html
- http://www.joomlatools.com/blog/2014/11/logman-2-api-documentation-available.html
- http://www.joomlatools.com/blog/2014/03/with-a-little-help-from-your-friends.html
- http://www.joomlatools.com/blog/2014/03/joomla-console.html

2. From http://www.nooku.org/blog

- http://www.nooku.org/blog/2015/06/backbone-joomla-and-nooku-an-instant-friendship/
- http://www.nooku.org/blog/2015/01/getting-started-with-nooku-and-our-tutorial-component/
- http://www.nooku.org/blog/2015/05/nooku-framework-21-released/
- http://www.nooku.org/blog/2015/02/custom-joomla-extensions-with-nooku/
- http://www.nooku.org/blog/2015/01/a-happy-nooku-year-to-all-of-you/
- http://www.nooku.org/blog/2014/12/special-delivery-from-the-composer-express/

Needs to be updated first 

- http://www.nooku.org/blog/2011/02/nginx-for-the-world-and-joomla/
- http://www.nooku.org/blog/2012/01/getting-started-with-foreign-keys/
- http://www.nooku.org/blog/2014/09/belgian-police-web-platform-uses-nooku/ (probably better moved to Timble)
- http://www.nooku.org/blog/2011/11/the-magic-of-primary-and-unique-keys/
- http://www.nooku.org/blog/2011/11/form-validation-with-nooku-framework/
- http://www.nooku.org/blog/2011/10/the-magic-of-file-uploads-with-com_files/
- http://www.nooku.org/blog/2011/08/say-hello-to-the-dynamic-module-injector/
- http://www.nooku.org/blog/2010/12/split-views-using-nooku-framework/

**Comment by tomjanssens** [comment]
Ready for review: http://developer.joomlatools.xxx/blog/

**Comment by johanjanssens** [comment]
@tom could we add a simple 'separator' above 'blog' in the left site navigation to note this is separate. Until we have the new nav in place ?

**Comment by johanjanssens** [comment]
@tomjanssens I reviewed the blog posts, found following references to Nooku to cleanup 

- http://developer.joomlatools.xxx/blog/2015/01/getting-started-our-tutorial-component.html at the bottom in 'Composer Support'

That's all.

**Comment by tomjanssens** [comment]
@robinpoort Can you have a look to the responsiveness of the menu?

Few issues:
* On some widths the main menu is gone (maybe because it has an extra menu item now)
* When opening the dropdown menu the submenu is on top
* We'll need to implement the horizontal Apple-style scrolling for the submenu

**Comment by tomjanssens** [comment]
Released: http://developer.joomlatools.com/blog/
