### ISSUE TITLE
[blog] Blog post joomla-console 1.4

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#66]
Blog post about the 1.4 release of joomla-console

**Comment by stevenrombauts** [comment]
@johanjanssens Draft for this blog post is up at [google drive](https://docs.google.com/a/timble.net/document/d/14dzudp5jFK4V0pdcKchFnnAyKsEGYq3ZYmC4LLC09YA/edit?usp=sharing). 

Let me know if this is good to go or not!

**Comment by johanjanssens** [comment]
@stevenrombauts  Reviewed, ready for publication.

**Comment by stevenrombauts** [comment]
Thanks @johanjanssens ! Discussed with @tomjanssens, he is wrapping up the new developer blog and we will publish it as soon as the new changes are up.

**Comment by stevenrombauts** [comment]
Released to the new blog!
