### ISSUE TITLE
Debugging Joomla sites with PhpStorm

### ISSUE THREAD

**Issue by amazeika** [joomlatools/developer.joomlatools.com#68]
A blog post for debugging Joomla sites on our Vagrant box using PhpStorm.

**Comment by tomjanssens** [comment]
@amazeika I slimmed down the article a little. 

I also suggest the remove the part that installs `joomlatools-todo` and `nooku-activities` to keep the focus solely on PhpStorm & Xdebug. Thoughts?

**Comment by amazeika** [comment]
@tomjanssens Could you please review the latest draft?. Text was further improved. I've removed some more content and the demostration now makes use of our Hello World component instead of todo which requires Nooku.

**Comment by stevenrombauts** [comment]
@amazeika Great work! I tested all the steps on the vagrant box and everything works as advertised :)

It's a very long post though, we might want to consider removing some bits or summarising the last paragraphs a bit more?  (the various debugging "options" and the "lessons learned" sections)

Changes back on staging at : developer.joomlatools.xxx/blog/2015/10/debugging-joomla-with-phpstorm.html

**Comment by johanjanssens** [comment]
@amazeika I agree with Steven, text is a tad long. Would try to make each para just a bit smaller. I would also remove the complete 'lessons learned' section. Bring it down to 

"PHPStorm offers great debugging capabilities for PHP. Once you have tried it, there is no coming back. That is a fact!"

**Comment by tomjanssens** [comment]
I slimmed down the article a little further and reduced the closing paragraphs.

Can you do a final review of http://developer.joomlatools.xxx/blog/2015/12/debugging-joomla-with-phpstorm.html?

**Comment by johanjanssens** [comment]
I like it. All good for me.

**Comment by tomjanssens** [comment]
Published: http://developer.joomlatools.com/blog/2015/12/debugging-joomla-with-phpstorm.html
