### ISSUE TITLE
New Joomlatools Vagrant released

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/developer.joomlatools.com#70]
New Joomlatools Vagrant (v1.4) released

**Comment by stevenrombauts** [comment]
@johanjanssens Added the texts about Joomla plugin for z-ray and mentioned Varnish Cache as we discussed. Could you take a look at http://developer.joomlatools.xxx/blog/2015/11/new-joomlatools-vagrant-released.html and see if its good to go?

@tomjanssens I've added some text so the blog has become a bit longer. Could you take a look and see if you agree on the changes too? Thanks

**Comment by johanjanssens** [comment]
@stevenrombauts All good. Excellent work! :)

**Comment by tomjanssens** [comment]
Released on production: http://developer.joomlatools.com/blog/2015/11/new-joomlatools-vagrant-released.html
