### ISSUE TITLE
Add newsletter subscribed page

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/developer.joomlatools.com#72]
Track newsletter sign-ups using a custom pages.

**Comment by tomjanssens** [comment]
Released: http://developer.joomlatools.com/newsletter/

**Comment by johanjanssens** [comment]
@tomjanssens  Are we integrating this somewhere ? or is this just for referencing purposes ?

**Comment by tomjanssens** [comment]
We're linking to that page from README's on GitHub and also from the http://developer.joomlatools.com/.

**Comment by johanjanssens** [comment]
Thanks!
