### ISSUE TITLE
[blog] Joomlatools Platform

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#73]
Blog post on release Joomlatools Platform

**Comment by stevenrombauts** [comment]
Draft in google docs [here](https://docs.google.com/a/timble.net/document/d/16HOZhAeRLdZCGyXMT7j1N2SWAvTbBtBc3OwkMWlSQSY/edit?usp=sharing).

**Comment by stevenrombauts** [comment]
@johanjanssens A draft for this blog post is available at [google docs](https://docs.google.com/a/timble.net/document/d/16HOZhAeRLdZCGyXMT7j1N2SWAvTbBtBc3OwkMWlSQSY/edit?usp=sharing).

There is much to be said but I'm not 100% what to include in the post and what not. As we discussed I focussed on the "Features" slides. Let me know your thoughts.

**Comment by johanjanssens** [comment]
@stevenrombauts Did some more work on the draft, can you have a look ?

**Comment by stevenrombauts** [comment]
@johanjanssens Thanks, introduction + 12 app paragraphs are much better now! Blog post drafted and available on staging: http://developer.joomlatools.xxx/blog/2015/11/introducing-joomlatools-platform.html

I would maybe remove a screenshot or two? Maybe remove the folder structure and page speed screenshots, and replace them with a link to the relevant slides @tomjanssens

**Comment by tomjanssens** [comment]
Published http://developer.joomlatools.com/blog/2015/11/introducing-joomlatools-platform.html
