### ISSUE TITLE
Magical anchor links for headers

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/developer.joomlatools.com#74]
Magically add links to headers like GitHub does.

**Comment by tomjanssens** [comment]
http://bryanbraun.github.io/anchorjs/

**Comment by tomjanssens** [comment]
Deployed, try http://developer.joomlatools.com/platform/12-factor-app.html for some magic powers.

**Comment by stevenrombauts** [comment]
Thanks Tom, awesome little feature :)

**Comment by johanjanssens** [comment]
Very nice and very handy!
