### ISSUE TITLE
Link to renamed repositories & packages

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/developer.joomlatools.com#78]
GitHub repositories will be renamed:

- joomla-vagrant -> joomlatools-vagrant
- joomla-console -> joomlatools-console
- joomla-platform -> joomlatools-platform
- joomla-composer -> joomlatools-composer
- joomla-console-backup -> joomlatools-console-backup
- joomla-console-capistrano -> joomlatools-console-capistrano

Packagist packages will be renamed:

- joomlatools/joomla-console -> joomlatools/console
- joomlatools/joomla-console-backup -> joomlatools/console-backup
- joomlatools/joomla-console-capistrano -> joomlatools/console-capistrano
- joomlatools/joomla-platform -> joomlatools/platform

**Comment by stevenrombauts** [comment]
All changes deployed to production at http://developer.joomlatools.com/
