### ISSUE TITLE
REST API docs

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#8]
See : http://www.joomlatools.com/membercenter/forums/topic/2118

Possible tools to use :

- https://developers.helloreverb.com/swagger/
- http://apiary.io/how-it-works
- https://github.com/mashery/iodocs
- http://apiblueprint.org/ -> looks very interesting

**Comment by stevenrombauts** [comment]
Have reviewed in detail the JSON API (jsonapi.org).  

Have put up a rough first draft of a general description of the structure of default JSON  documents produced by Nooku. 
https://docs.google.com/a/timble.net/document/d/1LCH9dmlMQ0dG7ZIadSCeQMiEUsTGKJj_nRwiSjjAbqs
Its conversational and general.

Will need to now focus on DOCman.

**Comment by stevenrombauts** [comment]
Excellent work Cameron. For DOCman as with Nooku we can focus on the json format in relation to retrieveing data first before we worry about none-GET requests.

**Comment by stevenrombauts** [comment]
Added : http://apiblueprint.org/

**Comment by stevenrombauts** [comment]
Hey Guys, 

First crack at the specific DOCman documentation. Its different because we have actual endpoints to work with and so, since I have used it before have gravitated towards apiary.io . 

http://docs.docmanjson.apiary.io/

I need to add some responses for some of the endpoints, change the 'lipsem' stuff to actual readable values and curate the various descriptions. But I think apiary will serve our purposes nicely. Once we have a url for the Nooku REST Json documentation I'm writing we can 
make some more reference there. 
What do you think about creating a 'generic' Nooku API doc of the same structure as a companion?

**Comment by stevenrombauts** [comment]
Good work Cameron. Ideas/questions :

1. For the Joomlatools documentation ideally we do not need to send our users offsite. Is the apiary.io solution something that we can run easily on developer.joomlatools.com and style to match ?

2. For the endpoints, would it make sense to hook the api demo into our demo site, so people can play with it and use our demo data ? We are launching complete new demo's sites with a lot of demo content.

3. The Nooku REST docs can go into the guides. Feel free to commit them. Just need to work out the structure abit. Can discuss that tomorrow. 

4. As for the generic Nooku API doc, not a bad idea, I was thinking to setup a Joomla demo site on Nooku which has com_tada installed. Could we add demo content there and use this as an endpoint ?

**Comment by stevenrombauts** [comment]
1. Apiary is really just a Blueprint API parser. It looks like there are several available that we can look at. http://apiblueprint.org/#get-started

2. Sure. Once that demo ready, its easy to edit the docs. In some places, you just need to edit the one url template. 

3. Great. 

4. We are already using com_tada in the Nooku REST docs (because it just makes sense). So, sure, we can use that output as example and refer to the urls as well.

**Comment by stevenrombauts** [comment]
1. True, forgot about that. Looks like https://github.com/danielgtaylor/aglio is the most active developed oen. This also looks interesting : https://github.com/renewablefunding/blueprint-docify

2. Great. Lets make that happen.

4. Great. Lets make that happen. I'll talk with the Steven if we can get a demo setup going.

**Comment by stevenrombauts** [comment]
@cameronbarr Noticed you assigned this back to me, are you looking for any specific feedback on this ?

**Comment by stevenrombauts** [comment]
@johanjanssens ,  mostly just to put it on your radar I think : https://github.com/joomlatools/api.joomlatools.com 

The package is done and it works, but maybe should reassign it to Robin or Tom to checkout my Jade template for Joomlatools before deploying and they can make any adjustments they see fit.  Also maybe a Rakefile similar to the Guides would be good.

**Comment by stevenrombauts** [comment]
Yep, lets continue to push this. If your work is done time to get this rolled out. Can you coordinate with @robin @tom to checkout your template and with @steven to plan roll out and infra changes where needed.

**Comment by johanjanssens** [comment]
See #64

**Comment by tomjanssens** [comment]
Discontinuing this issue, closing and marked as Invalid.

This issue and the mentioned https://github.com/joomlatools/api.joomlatools.com was nothing more than a self-hosted version of an API Blueprint Markdown file.

We have the same API Blueprint Markdown on Apairy.io: http://docs.joomlatoolsdocman.apiary.io/. Cool thing of Apiary.io is that is has a [Console](https://docs.apiary.io/tools/interactive-documentation/#console) that can get data from our demo server to test API calls.

The https://github.com/joomlatools/api.joomlatools.com repository has been removed. We will focus solely on our Apiary.io documentation.

**Comment by tomjanssens** [comment]
Apiary documention work continues in #82.
