### ISSUE TITLE
Document DOCman JSON output

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/developer.joomlatools.com#82]
Finish the Apiary documentation (http://docs.joomlatoolsdocman.apiary.io/) and link to it in our documentation.

**Comment by johanjanssens** [comment]
@tomjanssens We could probably do a docs.joomlatools.apiary.io and have all our docs there (in case we add more docs for other extensions) ?

**Comment by tomjanssens** [comment]
- Let's first focus on the DOCman documentation
- Apiary navigation has support for 2 levels, not ideal for listing all our extensions on one page
- No advantage in showing all API's on one page since all our extensions have their own documentation on our developer site

**Comment by johanjanssens** [comment]
Agreed.

**Comment by tomjanssens** [comment]
Removed the PHP and Event API content from the documentation, API Blueprint is not meant for this.

http://docs.joomlatoolsdocman.apiary.io/

**Comment by tomjanssens** [comment]
@ercanozkaya can you review http://docs.joomlatoolsdocman.apiary.io/#?

If documentation is ok I will add add a link on the site.

**Comment by johanjanssens** [comment]
@tom Edit a document is noted as a patch request, see: http://docs.joomlatoolsdocman.apiary.io/#reference/documents/document-object/edit-a-document This should be a POST request, or a PUT request. We do not support PATCH.

**Comment by tomjanssens** [comment]
Fixed.

**Comment by ercanozkaya** [comment]
@tomjanssens Shouldn't the Itemid be included in the URLs?

**Comment by johanjanssens** [comment]
@ercanozkaya Good question, technically, for frontend yes, for backend no, we can add it option for frontend URL's ?

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/58
