### ISSUE TITLE
Update template overrides guide

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/developer.joomlatools.com#85]
Remove old tutorials such as:
* How to remove the "Documents" heading?
* How to remove the "Categories" heading?
* How to remove the weekday from the date?

as they are not relevant anymore

**Comment by ercanozkaya** [comment]
@tomjanssens The guide is updated on staging:
http://developer.joomlatools.xxx/extensions/docman/templates/overrides.html#creating-css-overrides

**Comment by tomjanssens** [comment]
Deployed to production: http://developer.joomlatools.com/extensions/docman/templates/overrides.html
