### ISSUE TITLE
Legacy tab

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#86]
Add a Legacy tab:

* point out potentially breaking changes
* mention the legacy packages and legacy.sql file.

**Comment by johanjanssens** [comment]
@stevenrombauts  As discussed, if we can move the legacy.sql file to the legacy package and make it auto-install the sql this would make everything a lot smoother. You mentioned to use https://getcomposer.org/doc/articles/scripts.md#package-events

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/44
