### ISSUE TITLE
New DOCman guides

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/developer.joomlatools.com#87]
Blog post about the latest updates to the DOCman developer documentation

See: https://timble.assembla.com/spaces/joomlatools-docman/simple_planner#/ticket:903

**Comment by ercanozkaya** [comment]
@tomjanssens Can you review this?
http://developer.joomlatools.xxx/blog/2016/01/new-docman-guides.html

**Comment by tomjanssens** [comment]
Made a few changes, if those are ok for you, you can deploy to production.

**Comment by johanjanssens** [comment]
Looking all dandy to me.

**Comment by tomjanssens** [comment]
Closing, has been published some time ago: http://www.joomlatools.com/developer/blog/2016/01/new-docman-api-guides/.
