### ISSUE TITLE
Vagrant FAQ: private networks

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#89]
Some user (@ddavidov on Gitter) reported issues on Ubuntu 14.04 where the virtual network was not reachable from the host at all (not even ping), although `vagrant ssh`worked.

The solution was to have virtualbox recreate the private hosts. This could be useful addition to the faq: http://lucrussell.com/unable-to-connect-to-vagrant-guest-vms-in-a-private-network-2/

**Comment by tomjanssens** [comment]
Moved to https://github.com/joomlatools/www.joomlatools.com/issues/43
