### ISSUE TITLE
How to automatically create a document

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#9]
- http://www.joomlatools.com/membercenter/forums/topic/2150
- http://www.joomlatools.com/membercenter/forums/topic/3041-automated-document-generation-for-generated-files
- http://www.joomlatools.com/membercenter/forums/topic/3049
- http://www.joomlatools.com/membercenter/forums/topic/3112#comment-14335

**Comment by stevenrombauts** [comment]
Related to following user request for help. 

- https://docs.google.com/a/joomlatools.eu/document/d/18HFORzabZ-qo4TIP66F4OqCBDqrCaz91gJVatuSmHB8/edit
- https://docs.google.com/a/joomlatools.eu/document/d/1EZ4u9Y-j7l-E9YadnOmHQ1RmgoQgTQvQ2ZCBAooDj3w/edit

**Comment by stevenrombauts** [comment]
added 3 Gist snippets to replace his main DOCman functions:
* add a new document: https://gist.github.com/425247bc02f395c6f3ff
* get a list of documents: https://gist.github.com/75d22e17b5181e21123b
* get an HTML listbox of categories: https://gist.github.com/53bb701285d9f580dc95

@johanjanssens, listbox needs attention since the hidden input fields are visible

**Comment by stevenrombauts** [comment]
@matikochen Can you update the above snippets and add aditional inline documentation in each snippet instead of putting that into the title of the snippet ? 

Title should be something like DOCman 2.0 Stable - [Short title]

Further feedback 

<?
$catid = 2; //could also be an array(1,2,3,4)
 
$model = KObjectManager::getInstance()->getObject('com://admin/docman.model.documents')
    ->category($catid);
 
$list = $model->fetch();

This can be shorter 

$catid = 2; //could also be an array(1,2,3,4)
 
$documents = KObjectManager::getInstance()->getObject('com://admin/docman.model.documents')
    ->category($catid)
    ->fetch();
 
For https://gist.github.com/kochen/53bb701285d9f580dc95 -> Working on improving this so we can load the template file from anywhere.

**Comment by stevenrombauts** [comment]
@johanjanssens, is it ok now?

**Comment by stevenrombauts** [comment]
In https://gist.github.com/kochen/425247bc02f395c6f3ff  you can also replace JFactory::getUser() with a Koowa call. The call would be

 $user = KObjectMAnager::getInstance()->getObject('user');

In https://gist.github.com/kochen/75d22e17b5181e21123b

I would also include information about what the call returns. A call to to a model returns a KModelEntityRowset, where each item in the rowset is a KModelEntityRow. In case of the documents, it returns special document entities. User will need to know what properties are exposed by the document entity to be able to do something with the code.

**Comment by stevenrombauts** [comment]
I've added some comments.
looking at his code, he needs the document list just to go over the titles/filenames, break them down and see he doesn't create any duplication in the name (according to his format):

<pre><code>foreach ($documents as $doc) {
		$filename = pathinfo($doc->dmname, PATHINFO_FILENAME);
		preg_match("/(?<cat>[a-zA-Z0-9]{1,})(\s|_|\-|,)(?<type>[a-zA-Z0-9]{1,})(\s|_|\-|,)(?<year>[0-9]{2,4})(_|\-|,)(?<month>[0-9]{2})(_|\-|,)(?<day>[0-9]{2})/", $filename, $matches);
		...
}
</code></pre>

**Comment by stevenrombauts** [comment]
Could you also add this to the gists as per example ? The more we let him see how to do it, the less questions we will get.

**Comment by stevenrombauts** [comment]
Email send to customer. Moving to test.

**Comment by johanjanssens** [comment]
@ercanozkaya Assigning this to you. Here is the list of forum posts that also include information about this. 

- http://support.joomlatools.com/forums/topic/5428-file-addition-from-a-third-party-script
- http://support.joomlatools.com/forums/topic/5083-docman-rest-api
- http://support.joomlatools.com/forums/topic/5051-example-requests-in-docman-api
- http://support.joomlatools.com/forums/topic/4833-upload-documents-via-email

**Comment by johanjanssens** [comment]
@ercan http://support.joomlatools.com/forums/topic/5599 this is the forum post for the customer that needs dev support.

**Comment by ercanozkaya** [comment]
Can you review this sir? 
http://developer.joomlatools.xxx/extensions/docman/php-api.html

**Comment by johanjanssens** [comment]
@ercanozkaya Good work, you over delivered! Do we need to set the '"request" in the controllers ourselves all the time : 'request' =  $manager->getObject('request') Would be nice if this line could be omitted, code would become a lot cleaner and leaner ?

**Comment by johanjanssens** [comment]
@ercanozkaya The code for "Find the documents for a specific file" is performing a count it's not retrieving the documents itself. Maybe title should say, count the documents for a specific file. or change to browse() ?

**Comment by johanjanssens** [comment]
@ercanozkaya Would split it up into a category and document header. So it becomes clearer what the examples for the category and for the document are.

**Comment by ercanozkaya** [comment]
@johanjanssens  Done. Another review please?

**Comment by johanjanssens** [comment]
I would still try to make it a bit easier to read, for example:

    $result = KObjectManager::getInstance()->getObject('com://site/docman.controller.document')
->id($document_id)
->delete();

**Comment by ercanozkaya** [comment]
@johanjanssens Done as well. Shall we deploy it?

**Comment by johanjanssens** [comment]
@ercanozkaya See feedback on chat. A little bit more cleaning todo, would put it all on separate lines to prevent scrolling as much as possible.

**Comment by johanjanssens** [comment]
Note, forums have been updated, tickets marked as ready, customers that no longer have an active subscription have received a personal email with info about the new docs. Good work!
